image: python:3.10

before_script:
  - python --version
  - pip install --upgrade pip "poetry==1.5.1"
  - poetry config virtualenvs.create false --local
  - poetry install --no-ansi


# List of stages for jobs, and their order of execution
stages:
  - testing
  - build
  - deploy

test:
  stage: testing
  script:
    - echo "Test done..."

lint:
  stage: testing
  script:
    - echo "Lint done..."


make-build:
  stage: build
  script:
    - echo "Make build..."

deploy:
  stage: deploy
  script:
    - echo "Deploy ..."