image: python:3.10

before_script:
  # install dependencies for cv2
  - apt-get update && apt-get install libgl1 -y
  - apt-get install libopenblas-dev -y

  # check python version
  - python --version

  # install all project dependencies
  - pip install --upgrade pip "poetry==1.5.1"
  - poetry config virtualenvs.create false --local
  - poetry install --no-ansi


# List of stages for jobs, and their order of execution
stages:
  - testing
#  - build
#  - deploy

test:
  stage: testing
  services:
    - postgres
  variables:
    SECRET_KEY: ${SECRET_KEY}
    POSTGRES_DB: pro_platform
    POSTGRES_USER: soren
    POSTGRES_PASSWORD: pass123
    CONFIG_CLASS: TestingConfig
    SKIP_API_TESTS_ACTIONS: 1
    COVERAGE_DIR: "coverage-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
  script:
    - cd pro_platform
    - python manage.py migrate
    - coverage run manage.py test -v 2 && coverage report
    - coverage html -d $COVERAGE_DIR
  artifacts:
    name: "coverage-report-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - /builds/otus_projects/professionalplatform/pro_platform/$COVERAGE_DIR
    when: on_success
    expire_in: 1 week

#  stage: testing
#  script:
#    - echo "Lint done..."
#
#make-build:
#  stage: build
#  script:
#    - echo "Make build..."
#
#deploy:
#  stage: deploy
#  script:
#    - echo "Deploy ..."