name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

#env:
#  DEBUG: ${DEBUG}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: pro_platform
          POSTGRES_USER: soren
          POSTGRES_PASSWORD: pass123
        ports:
          - 9999:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install --upgrade pip "poetry==1.5.1"
        poetry config virtualenvs.create false --local
        poetry install --no-ansi
    - name: Run Tests
      working-directory: ./pro_platform
      run: |
        python manage.py test
